#!/usr/bin/env bash

#### Sonar - A WiFi Keepalive daemon
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022
#### https://github.com/mainsail-crew/sonar
####
#### This File is distributed under GPLv3
####

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Installing sonar ..."

## Force apt update
apt-get update
## Make sure 'git' is installed!
check_install_pkgs git

## Step 1: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 2: clone sonar repo
echo_green "Clone sonar repository ..."
sudo -u "${BASE_USER}" git clone -b "${SONAR_REPO_BRANCH}" --depth 1 \
    "${SONAR_REPO_SHIP}" sonar

## Step 3: install dependencies
# Upstream tools/install.sh no longer defines PKGLIST= (it uses a local pkglist array).
# Match install_packages() there: iputils-ping
echo_green "Install sonar dependencies ..."
check_install_pkgs iputils-ping

## Step 4: Move to sonar as working directory
pushd "/home/${BASE_USER}/sonar" &> /dev/null || exit 1

## Step 5: Run sonar install routine
echo_green "Launch sonar install routine ..."
make install

## Step 6: Leave sonar
popd &> /dev/null || exit 1

## Step 7: leave home dir
popd &> /dev/null || exit 1

## Step 8:
echo_green "Enable sonar.service ..."
systemctl_if_exists enable sonar.service

## Finish
echo_green "Installing sonar ... DONE!"
